// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwdapguaoueiqkryyfkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3ZGFwZ3Vhb3VlaXFrcnl5ZmtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMzg3NDgsImV4cCI6MjA1NDgxNDc0OH0.mi5RlffM3LY47d885VqcCHb6ffoAWcBFWltTZuG0WxU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);